// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBM4XafD522jl2Qxibpzwzh4YER07Gdfo',
    appId: '1:358157670459:ios:99deb909ff5f28ac23241e',
    messagingSenderId: '358157670459',
    projectId: 'greenlens-b5dc4',
    storageBucket: 'greenlens-b5dc4.firebasestorage.app',
    iosBundleId: 'com.example.greenlens',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EdtprwiLNAZGEcYG-1sDuFs-eqd2EjA',
    appId: '1:358157670459:android:d28b6143e348132c23241e',
    messagingSenderId: '358157670459',
    projectId: 'greenlens-b5dc4',
    storageBucket: 'greenlens-b5dc4.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xH_UVyoQZ1ADhlA226ikE2fbRDJAMUk',
    appId: '1:358157670459:web:a65dd04858bcc03f23241e',
    messagingSenderId: '358157670459',
    projectId: 'greenlens-b5dc4',
    authDomain: 'greenlens-b5dc4.firebaseapp.com',
    storageBucket: 'greenlens-b5dc4.firebasestorage.app',
    measurementId: 'G-QFFWP7LGH4',
  );

}